### ISSUE TITLE
pyramidbox_lite_server_mask can't be converted to onnx model

### ISSUE THREAD

**Issue by lunasdejavu** [PaddlePaddle/Paddle2ONNX#137]
mapyramidbo_lite has an error 

and mask_detector  successsed but the architecture is wrong by being visualized by Netron

**Comment by Channingss** [comment]
@lunasdejavu please send the model or code of mode to us (chen_lingchi@163.com)

**Comment by Channingss** [comment]
We tested the two models you sent to us. After trying to convert:
1. pyramidbox_lite reported errors due to lack support for operator::`density_prior_box`. 
2. mask_detector converted and inferenced by `onnxruntime` successsfully. I don't quite understand what you said there was an error in the visualization after converting to the ONNX model.

**Comment by lunasdejavu** [comment]
https://imgur.com/gallery/TnAVpBu
 by the visualizations of netron
the architectures are all different and there are always a reshape layer add with the convolution layers. it doesn't look right

**Comment by Channingss** [comment]
@lunasdejavu Because the broadcast implementation of onnx is different with paddle. The bias should reshaped to support ADD operator with convolution's output, which is compatible for  broadcast mechanism of onnx. 
During the conversion, It's a normal performance that some Paddle OPs may be realized by a combination of multiple ONNX OP.
