### ISSUE TITLE
PaddleOCR中文表格模型转onnx缺失算子支持

### ISSUE THREAD

**Issue by 746891300-org** [PaddlePaddle/Paddle2ONNX#878]
PaddleOCR新出的中文表格识别模型转onnx报错：
NotImplementedError: 
There's 5 ops are not supported yet
=========== tensor_array_to_tensor ===========
=========== lod_array_length ===========
=========== while ===========
=========== write_to_array ===========
=========== one_hot_v2 ===========

模型地址：
https://paddleocr.bj.bcebos.com/ppstructure/models/slanet/ch_ppstructure_mobile_v2.0_SLANet_infer.tar

**Comment by yeliang2258** [comment]
你好，这个模型要转换成功，需要OCR模型去除控制流，建议去PaddleOCR repo下提issue，去除该模型的控制流之后再进行转换

**Comment by 746891300-org** [comment]
好的，谢谢！

**Comment by mingo-doer** [comment]
@yeliang2258  你好   这个模型也是一样的问题吗？https://paddleocr.bj.bcebos.com/dygraph_v2.0/table/en_ppocr_mobile_v2.0_table_structure_infer.tar 
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: /root/ocr/inference/en_ppocr_mobile_v2.0_table_structure_infer/inference.pdmodel
[Paddle2ONNX] Paramters file path: /root/ocr/inference/en_ppocr_mobile_v2.0_table_structure_infer/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] LodTensorArray is not supported.
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,lod_array_length,select_input,tensor_array_to_tensor,while,write_to_array,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)

**Comment by WenmuZhou** [comment]
fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/7485, the inference model has also been updated,  you can re-download it for paddle2onnx

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324

**Comment by Zheng-Bicheng** [comment]
已经更新支持 while 算子，等待 CI 结束后 安装 Paddle2ONNX v1.2.10 使用:

* https://github.com/PaddlePaddle/Paddle2ONNX/actions/runs/11362622694
