### ISSUE TITLE
ppyoloe_r_crn_s_3x_spine 转onnx报错

### ISSUE THREAD

**Issue by CachCheng** [PaddlePaddle/Paddle2ONNX#970]
paddle2onnx --model_dir output_inference/ppyoloe_r_crn_s_3x_spine \
>             --model_filename model.pdmodel \
>             --params_filename model.pdiparams \
>             --save_file output_inference/ppyoloe_r_crn_s_3x_spine/model.onnx \
> 

[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: output_inference/ppyoloe_r_crn_s_3x_spine/model.pdmodel
[Paddle2ONNX] Paramters file path: output_inference/ppyoloe_r_crn_s_3x_spine/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [nearest_interp_v2: nearest_interp_v2_0.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [nearest_interp_v2: nearest_interp_v2_1.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_0.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_1.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_2.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_3.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_4.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_5.tmp_0] Requires the minimal opset version of 11.
[ERROR][Paddle2ONNX] [multiclass_nms3: multiclass_nms3_0.tmp_1] The 2-nd and 3-rd dimension of input bboxes tensor of multiclass_nms should be fixed, but now the shape is [-1, -1, 8].
[Paddle2ONNX] Due to the operator: multiclass_nms3, this model cannot be exported to ONNX.
[Paddle2ONNX] Due to the operator: nearest_interp_v2, requires opset_version >= 11.
[ERROR] Model exporting failed, you can report this problem to https://github.com/PaddlePaddle/Paddle2ONNX.git.
已放弃 (核心已转储)

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle
可以先用这个工具将paddle模型的input shape先定下来，然后再来导出

**Comment by thunder95** [comment]
> https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle 可以先用这个工具将paddle模型的input shape先定下来，然后再来导出

@yeliang2258 已经固定shape，仍然出现楼主的报错

# paddle2onnx
!paddle2onnx --model_dir /home/aistudio/PaddleDetection/new_model \
            --model_filename model.pdmodel \
            --params_filename model.pdiparams \
            --save_file ppyoloe_r_crn_s_3x_dota.onnx \
            --enable_dev_version True
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: /home/aistudio/PaddleDetection/new_model/model.pdmodel
[Paddle2ONNX] Paramters file path: /home/aistudio/PaddleDetection/new_model/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [nearest_interp_v2: nearest_interp_v2_0.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [nearest_interp_v2: nearest_interp_v2_1.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_0.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_1.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_2.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_3.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_4.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_5.tmp_0] Requires the minimal opset version of 11.
[ERROR][Paddle2ONNX] [multiclass_nms3: multiclass_nms3_0.tmp_1] The 2-nd and 3-rd dimension of input bboxes tensor of multiclass_nms should be fixed, but now the shape is [-1, -1, 8].
[Paddle2ONNX] Due to the operator: multiclass_nms3, this model cannot be exported to ONNX.
[Paddle2ONNX] Due to the operator: nearest_interp_v2, requires opset_version >= 11.
[ERROR] Model exporting failed, you can report this problem to https://github.com/PaddlePaddle/Paddle2ONNX.git.
